cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7562724
  brandStrength: 0.797491
  lightness: 0.7885305
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 0.7455197
typography_spectrum: 0.7544803
layout_spectrum: 0.7903226
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: GreaterAlexander
